Upgrade Angular to 17.1
claes-distribution/store-app pull request #11
Opened 2024-02-14 07:42 UTC by LuckyWraptor

2024-02-14 10:08 UTC, JamieVangeysel requested changes
fix @schematics/angular

2024-02-14 10:08 UTC, JamieVangeysel commented on package.json
>      "@schematics/angular": "^14.2.13",
why is this still on 14 🫣

2024-02-14 10:16 UTC, LuckyWraptor commented on package.json
>      "@schematics/angular": "^14.2.13",
You mistyped "LGTM"

2024-02-15 13:33 UTC, JamieVangeysel approved these changes

2024-02-15 13:34 UTC, merged